controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|de'
    defaults:
        _locale: 'en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
